from typing import List, Dict

ENTERPRISES: List[Dict] = [
    {
        "id": "costurando-sonhos",
        "name": "Costurando Sonhos",
        "category": "Moda",
        "cover_image": "https://www.ufsm.br/app/uploads/sites/570/2025/10/costurando-sonhos-1024x1024.jpg",
        "short_description": "Peças de costura criativa e customização, transformando tecidos em arte vestível.",
        "full_description": "Costurando Sonhos é um empreendimento de Elisandra Rodrigues Dutra, dedicado à confecção de peças únicas de moda e costura criativa.",
        "whatsapp": "55991234567",
        "instagram": "@costurandosonhos",
        "email": "costurandosonhos@email.com",
        "tags": ["costura", "moda", "customização", "artesanal"],
        "products": [
            {"id": "cs-1", "name": "Vestido Customizado", "description": "Vestido exclusivo com bordados e aplicações artesanais, peça única.", "price": 180.0, "image": "https://images.unsplash.com/photo-1595777457583-95e059d581b8"},
            {"id": "cs-2", "name": "Bolsa de Tecido Personalizada", "description": "Bolsa feita em tecido resistente com estampa exclusiva.", "price": 85.0, "image": "https://images.unsplash.com/photo-1590874103328-eac38a683ce7"},
            {"id": "cs-3", "name": "Jaqueta Customizada", "description": "Jaqueta jeans com customização única.", "price": 220.0, "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5"},
        ],
    },
    {
        "id": "mimos-artesanatos-jura",
        "name": "Mimos e Artesanatos da Jura",
        "category": "Artesanato",
        "cover_image": "https://www.ufsm.br/app/uploads/sites/570/2025/10/mimos-e-artesanatos-da-jura-1024x1024.jpg",
        "short_description": "Artesanatos encantadores feitos com carinho.",
        "full_description": "Mimos e Artesanatos da Jura é o empreendimento de Juraci Terezinha Antunes Ribeiro Licht.",
        "whatsapp": "55992345678",
        "instagram": "@mimosdajura",
        "tags": ["artesanato", "decoração", "mimo", "presente"],
        "products": [
            {"id": "maj-1", "name": "Boneca de Pano", "description": "Boneca artesanal feita em tecido.", "price": 65.0, "image": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64"},
            {"id": "maj-2", "name": "Almofada Decorativa", "description": "Almofada com capa em tecido estampado.", "price": 48.0, "image": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc"},
            {"id": "maj-3", "name": "Centro de Mesa Artesanal", "description": "Peça decorativa para centro de mesa.", "price": 72.0, "image": "https://images.unsplash.com/photo-1509233725247-49e657c54213"},
        ],
    },
    {
        "id": "raquel-dellinghausen",
        "name": "Raquel Dellinghausen",
        "category": "Artesanato",
        "cover_image": "https://www.ufsm.br/app/uploads/sites/570/2025/10/raquel-1024x1024.jpg",
        "short_description": "Arte em cerâmica e esculturas delicadas.",
        "full_description": "Raquel Dellinghausen é uma artista que trabalha com cerâmica e esculturas.",
        "whatsapp": "55993456789",
        "instagram": "@raqueldellinghausen.arte",
        "email": "raquel.art@email.com",
        "tags": ["cerâmica", "escultura", "arte", "decoração"],
        "products": [
            {"id": "rd-1", "name": "Vaso Esculpido em Cerâmica", "description": "Vaso artesanal modelado à mão.", "price": 145.0, "image": "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61"},
            {"id": "rd-2", "name": "Escultura Decorativa", "description": "Escultura em cerâmica com acabamento esmaltado.", "price": 195.0, "image": "https://images.unsplash.com/photo-1604077350545-3f8a78b0db2e"},
            {"id": "rd-3", "name": "Conjunto de Tigelas Cerâmicas", "description": "Conjunto de 3 tigelas em cerâmica artesanal.", "price": 128.0, "image": "https://images.unsplash.com/photo-1610701596007-11502861dcfa"},
        ],
    },
    {
        "id": "vitrine-sustentavel",
        "name": "Vitrine Sustentável",
        "category": "Reciclagem",
        "cover_image": "https://www.ufsm.br/app/uploads/sites/570/2025/10/vitrine-sustentavel-1024x1024.jpg",
        "short_description": "Produtos sustentáveis e ecológicos.",
        "full_description": "Vitrine Sustentável é o projeto de Leandro Marcus Flores.",
        "whatsapp": "55994567890",
        "instagram": "@vitrinesustentavel",
        "tags": ["sustentável", "reciclagem", "upcycling", "ecológico"],
        "products": [
            {"id": "vs-1", "name": "Luminária de Garrafa PET", "description": "Luminária criativa feita com garrafa PET reciclada.", "price": 58.0, "image": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15"},
            {"id": "vs-2", "name": "Porta-Trecos Reciclado", "description": "Organizador de mesa feito com materiais reciclados.", "price": 42.0, "image": "https://images.unsplash.com/photo-1487700160041-babef9c3cb55"},
            {"id": "vs-3", "name": "Bolsa Ecológica de Lona", "description": "Bolsa resistente feita com lona reutilizada.", "price": 95.0, "image": "https://images.unsplash.com/photo-1547949003-9792a18a2601"},
        ],
    },
    {
        "id": "vedome-co",
        "name": "Vedome Co",
        "category": "Moda",
        "cover_image": "https://www.ufsm.br/app/uploads/sites/570/2025/10/vedome-co-1024x1024.jpg",
        "short_description": "Moda vegana e consciente.",
        "full_description": "Vedome Co é o empreendimento de Vanessa Paese Maltez.",
        "whatsapp": "55995678901",
        "instagram": "@vedome.co",
        "email": "vedome@email.com",
        "tags": ["vegano", "moda", "sustentável", "consciente"],
        "products": [
            {"id": "vc-1", "name": "Mochila Vegana", "description": "Mochila em couro vegetal.", "price": 165.0, "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62"},
            {"id": "vc-2", "name": "Cinto de Cortiça", "description": "Cinto feito em cortiça natural.", "price": 78.0, "image": "https://images.unsplash.com/photo-1624222247344-550fb60583bb"},
            {"id": "vc-3", "name": "Carteira Sustentável", "description": "Carteira compacta em material vegano.", "price": 55.0, "image": "https://images.unsplash.com/photo-1627123424574-724758594e93"},
        ],
    },
    {
        "id": "delicias-ana-gourmet",
        "name": "Delícias da Ana Gourmet",
        "category": "Alimentação",
        "cover_image": "https://www.ufsm.br/app/uploads/sites/570/2026/03/Logos-empreendimento-2025-1024x1024.jpg",
        "short_description": "Doces e salgados gourmet.",
        "full_description": "Delícias da Ana Gourmet é o empreendimento de Ana Julia Maciel Cardoso.",
        "whatsapp": "55996789012",
        "instagram": "@deliciasdaana",
        "email": "deliciasdaana@email.com",
        "tags": ["gourmet", "doces", "salgados", "artesanal"],
        "products": [
            {"id": "dag-1", "name": "Brownie Gourmet", "description": "Brownie artesanal com chocolate belga.", "price": 28.0, "image": "https://images.unsplash.com/photo-1607920591413-4ec007e70023"},
            {"id": "dag-2", "name": "Kit Festa Salgados", "description": "Kit com variedade de salgados gourmet.", "price": 145.0, "image": "https://images.unsplash.com/photo-1541529086526-db283c563270"},
            {"id": "dag-3", "name": "Torta de Limão Siciliano", "description": "Torta cremosa de limão siciliano.", "price": 68.0, "image": "https://images.unsplash.com/photo-1519915028121-7d3463d20b13"},
        ],
    },
    {
        "id": "harmonia-preta",
        "name": "Projeto Harmonia Preta",
        "category": "Moda",
        "cover_image": "https://www.ufsm.br/app/uploads/sites/570/2025/10/harmonia-preta-1024x1024.jpg",
        "short_description": "Moda afrocentrada e acessórios culturais.",
        "full_description": "Projeto Harmonia Preta é conduzido por Cátia Cilene Morais Dutra.",
        "whatsapp": "55997890123",
        "instagram": "@harmoniapr eta",
        "tags": ["afrocentrado", "cultura", "identidade", "acessórios"],
        "products": [
            {"id": "hp-1", "name": "Turbante Estampado", "description": "Turbante em tecido africano.", "price": 45.0, "image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f"},
            {"id": "hp-2", "name": "Colar de Búzios", "description": "Colar artesanal feito com búzios.", "price": 58.0, "image": "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f"},
            {"id": "hp-3", "name": "Brincos Afro", "description": "Brincos artesanais inspirados na cultura africana.", "price": 32.0, "image": "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908"},
        ],
    },
    {
        "id": "cia-diacono",
        "name": "Projeto Cia Diácono",
        "category": "Artesanato",
        "cover_image": "https://www.ufsm.br/app/uploads/sites/570/2025/10/cia-diacono-1024x1024.jpg",
        "short_description": "Coletivo artístico que cria peças teatrais.",
        "full_description": "Projeto Cia Diácono, coordenado por Mailon Rodrigues Marques.",
        "whatsapp": "55998901234",
        "instagram": "@ciadiacono",
        "email": "ciadiacono@email.com",
        "tags": ["teatro", "cultura", "coletivo", "educação"],
        "products": [
            {"id": "cd-1", "name": "Máscara Teatral Artesanal", "description": "Máscara decorativa inspirada em teatro popular.", "price": 72.0, "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d"},
            {"id": "cd-2", "name": "Poster de Peça Teatral", "description": "Poster ilustrado de produção teatral.", "price": 35.0, "image": "https://images.unsplash.com/photo-1594908900066-3f47337549d8"},
            {"id": "cd-3", "name": "Livro de Dramaturgia", "description": "Livro com textos autorais do coletivo.", "price": 48.0, "image": "https://images.unsplash.com/photo-1544947950-fa07a98d237f"},
        ],
    },
    {
        "id": "conecta-baoba",
        "name": "Conecta e Baobá",
        "category": "Cosmética",
        "cover_image": "https://www.ufsm.br/app/uploads/sites/570/2025/10/conecta-1-1024x1024.jpg",
        "short_description": "Cosméticos naturais com ingredientes da biodiversidade.",
        "full_description": "Conecta e Baobá é o empreendimento de Grazielle Gonçalves da Fonseca.",
        "whatsapp": "55999012345",
        "instagram": "@conectaebaoba",
        "email": "conectaebaoba@email.com",
        "tags": ["cosméticos", "natural", "baobá", "biodiversidade"],
        "products": [
            {"id": "cb-1", "name": "Óleo de Baobá", "description": "Óleo puro de baobá, hidratante natural.", "price": 52.0, "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108"},
            {"id": "cb-2", "name": "Manteiga Corporal Natural", "description": "Manteiga hidratante com manteiga de karité e baobá.", "price": 68.0, "image": "https://images.unsplash.com/photo-1556228841-a0a1374d0d9e"},
            {"id": "cb-3", "name": "Shampoo Sólido Biodiversidade", "description": "Shampoo em barra sem sulfatos.", "price": 38.0, "image": "https://images.unsplash.com/photo-1595348020949-87cdfbb44174"},
        ],
    },
]

USERS = [
    {"id": "admin-1", "email": "admin@hubis.ufsm.br", "password": "senhaadmin", "name": "Administrador Hub IS", "role": "admin", "active": True},
    {"id": "owner-1", "email": "costurandosonhos@email.com", "password": "senhaempreendedor", "name": "Elisandra Rodrigues Dutra", "role": "owner", "enterprise_id": "costurando-sonhos", "active": True},
    {"id": "owner-2", "email": "jura@email.com", "password": "senhaempreendedor", "name": "Juraci Licht", "role": "owner", "enterprise_id": "mimos-artesanatos-jura", "active": True},
    {"id": "owner-3", "email": "raquel.art@email.com", "password": "senhaempreendedor", "name": "Raquel Dellinghausen", "role": "owner", "enterprise_id": "raquel-dellinghausen", "active": True},
    {"id": "owner-4", "email": "vitrinesustentavel@email.com", "password": "senhaempreendedor", "name": "Leandro Marcus Flores", "role": "owner", "enterprise_id": "vitrine-sustentavel", "active": True},
    {"id": "owner-5", "email": "vedome@email.com", "password": "senhaempreendedor", "name": "Vanessa Paese Maltez", "role": "owner", "enterprise_id": "vedome-co", "active": True},
    {"id": "owner-6", "email": "deliciasdaana@email.com", "password": "senhaempreendedor", "name": "Ana Julia Maciel Cardoso", "role": "owner", "enterprise_id": "delicias-ana-gourmet", "active": True},
    {"id": "owner-7", "email": "harmonia@email.com", "password": "senhaempreendedor", "name": "Cátia Cilene Morais Dutra", "role": "owner", "enterprise_id": "harmonia-preta", "active": True},
    {"id": "owner-8", "email": "ciadiacono@email.com", "password": "senhaempreendedor", "name": "Mailon Rodrigues Marques", "role": "owner", "enterprise_id": "cia-diacono", "active": True},
    {"id": "owner-9", "email": "conectaebaoba@email.com", "password": "senhaempreendedor", "name": "Grazielle Gonçalves da Fonseca", "role": "owner", "enterprise_id": "conecta-baoba", "active": True},
]
